version: "3.9"
services:
  app:
    build: .
    container_name: task_manager_app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db/taskdb
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: task_manager_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - taskdb_data:/var/lib/postgresql/data
    ports:
      - "8501:8501"

  redis:
    image: redis:latest
    container_name: task_manager_redis
    ports:
      - "6379:6379"

volumes:
  taskdb_data:
